name: M1_5epoch
seed: 123
work_dir: .
log_dir: results/m1_5epoch/logs
model_dir: results/m1_5epoch/models
checkpoints_dir: results/m1_5epoch/checkpoints
results_dir: results/m1_5epoch/metrics
train_file: data/m1/train.xyz
valid_file: data/m1/valid.xyz
test_file: data/m1/test_internal.xyz
foundation_model: .mace-cache/mace/20231210mace128L0_energy_epoch249model
multiheads_finetuning: false
E0s: foundation
energy_key: REF_energy
forces_key: REF_forces
loss: weighted
energy_weight: 10.0
forces_weight: 100.0
batch_size: 2
valid_batch_size: 2
lr: 0.00001
weight_decay: 0.0000005
max_num_epochs: 5
patience: 5
eval_interval: 1
ema: true
ema_decay: 0.999
swa: false
device: cpu
default_dtype: float64
num_workers: 0
pin_memory: false
save_cpu: true
plot: false
skip_evaluate_heads: Default
log_level: INFO
